# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.8
  - scikit-learn=1.0
  - matplotlib=3.4.3
  - numpy=1.21.2
  - pip:
    - azureml-defaults==1.35.0
channels:
  - conda-forge
