name: Infra Deployment and Training

on:
  push:
    paths: 
      - '.github/workflows/train_model.yml' 
      - 'code/**' 
  repository_dispatch:
   types: [storage-blobcreated, storage-blobdeleted]

jobs:
  deployment:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
      
      # Connect the Azure Machine Learning Workspace
    - name: Connect Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: Azure/aml-compute@v1
      id: aml_compute
      with:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          
    # # Register model in Azure Machine Learning model registry
    - name: Register model
      id: aml_registermodel
      uses: Azure/aml-registermodel@ashishonce/adddefaulttags
      with:
         azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
         run_id:  ${{ steps.aml_run.outputs.run_id }}
         experiment_name: ${{ steps.aml_run.outputs.experiment_name }}

    # Deploy your model to dev (this is optional)
    #- name: Dev Deploy
    #  id: aml_dev_deploy
    #  uses: Azure/aml-deploy@v1
    #  with:
    #    azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #    model_name:  "${{ steps.aml_registermodel.outputs.model_name }}"
    #    model_version: "${{ steps.aml_registermodel.outputs.model_version }}"
    #    parameters_file: "deploy_aci.json"
      
    #- name: Display Aci Deploy Details
    #  run: |
    #    echo scoring-endpoint: ${{ steps.aml_dev_deploy.outputs.service_scoring_uri}}
    #    echo swagger-uri: ${{ steps.aml_dev_deploy.outputs.service_swagger_uri}}
     # Deploy your model to production
    - name: Prod Deploy
      id: aml_prod_deploy
      uses: Azure/aml-deploy@v1
      with:
         azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
         model_name:  "${{ steps.aml_registermodel.outputs.model_name }}"  
         model_version: "${{ steps.aml_registermodel.outputs.model_version }}"
         parameters_file: "deploy_aks.json"

    - name: Display AKS Deploy Details
      run: |
         echo scoring-endpoint: ${{ steps.aml_prod_deploy.outputs.service_scoring_uri}}
         echo swagger-uri: ${{ steps.aml_prod_deploy.outputs.service_swagger_uri}}
    
    
